# Generated by Django 2.2.5 on 2019-09-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('balance', models.FloatField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
