# Generated by Django 2.1.3 on 2019-05-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=50)),
                ('closed', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
